const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users", 
      required: true,
    },
    gameId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "games", 
      required: true,
    },
    orderId: {
      type: String, // The ID generated by Razorpay 
      required: true,
      unique: true,
    },
    paymentId: {
      type: String, // The ID generated after payment success (e.g., pay_PrvY...)
      default: null,
    },
    signature: {
      type: String, // Razorpay signature for security auditing
      default: null,
    },
    amount: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      enum: ["Pending", "Successful", "Failed"],
      default: "Pending", // Every order starts as Pending
    },
  },
  { timestamps: true } // Automatically adds createdAt and updatedAt
);

// Prevent model re-definition errors
const paymentModel =
  mongoose.models.payments || mongoose.model("payments", paymentSchema);

module.exports = paymentModel;